/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -a /home/uos/dev/panel-dev/src/dbusinterface/lockadaptor -c DBusLockAdaptor /home/uos/dev/panel-dev/misc/com.deepin.dde.lockFront.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef LOCKADAPTOR_H
#define LOCKADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.DBusLockAgent
 */
class DBusLockAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.DBusLockAgent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.DBusLockAgent\">\n"
"    <signal name=\"Visible\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"visible\"/>\n"
"    </signal>\n"
"    <signal name=\"Authenticate\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"    </signal>\n"
"    <method name=\"Show\"/>\n"
"    <method name=\"Hide\"/>\n"
"    <method name=\"LockVisible\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"LockAuthenticating\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DBusLockAdaptor(QObject *parent);
    virtual ~DBusLockAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Hide();
    bool LockAuthenticating();
    bool LockVisible();
    void Show();
Q_SIGNALS: // SIGNALS
    void Authenticate(bool result);
    void Visible(bool visible);
};

#endif
