/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -a /home/uos/dev/panel-dev/src/dbusinterface/lockadaptor -c DBusLockAdaptor /home/uos/dev/panel-dev/misc/com.deepin.dde.lockFront.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "/home/uos/dev/panel-dev/src/dbusinterface/lockadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusLockAdaptor
 */

DBusLockAdaptor::DBusLockAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusLockAdaptor::~DBusLockAdaptor()
{
    // destructor
}

void DBusLockAdaptor::Hide()
{
    // handle method call local.DBusLockAgent.Hide
    QMetaObject::invokeMethod(parent(), "Hide");
}

bool DBusLockAdaptor::LockAuthenticating()
{
    // handle method call local.DBusLockAgent.LockAuthenticating
    bool out0;
    QMetaObject::invokeMethod(parent(), "LockAuthenticating", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool DBusLockAdaptor::LockVisible()
{
    // handle method call local.DBusLockAgent.LockVisible
    bool out0;
    QMetaObject::invokeMethod(parent(), "LockVisible", Q_RETURN_ARG(bool, out0));
    return out0;
}

void DBusLockAdaptor::Show()
{
    // handle method call local.DBusLockAgent.Show
    QMetaObject::invokeMethod(parent(), "Show");
}

