/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -a /home/uos/dev/panel-dev/src/dbusinterface/shutdownadaptor -c DBusShutdownAdaptor /home/uos/dev/panel-dev/misc/com.deepin.dde.shutdownFront.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "/home/uos/dev/panel-dev/src/dbusinterface/shutdownadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusShutdownAdaptor
 */

DBusShutdownAdaptor::DBusShutdownAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusShutdownAdaptor::~DBusShutdownAdaptor()
{
    // destructor
}

void DBusShutdownAdaptor::Restart()
{
    // handle method call local.DBusShutdownAgent.Restart
    QMetaObject::invokeMethod(parent(), "Restart");
}

void DBusShutdownAdaptor::Show()
{
    // handle method call local.DBusShutdownAgent.Show
    QMetaObject::invokeMethod(parent(), "Show");
}

void DBusShutdownAdaptor::Shutdown()
{
    // handle method call local.DBusShutdownAgent.Shutdown
    QMetaObject::invokeMethod(parent(), "Shutdown");
}

bool DBusShutdownAdaptor::ShutdownVisible()
{
    // handle method call local.DBusShutdownAgent.ShutdownVisible
    bool out0;
    QMetaObject::invokeMethod(parent(), "ShutdownVisible", Q_RETURN_ARG(bool, out0));
    return out0;
}

