/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -a /home/uos/dev/panel-dev/src/dbusinterface/shutdownadaptor -c DBusShutdownAdaptor /home/uos/dev/panel-dev/misc/com.deepin.dde.shutdownFront.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SHUTDOWNADAPTOR_H
#define SHUTDOWNADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.DBusShutdownAgent
 */
class DBusShutdownAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.DBusShutdownAgent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.DBusShutdownAgent\">\n"
"    <method name=\"Shutdown\"/>\n"
"    <method name=\"Restart\"/>\n"
"    <method name=\"Show\"/>\n"
"    <method name=\"ShutdownVisible\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DBusShutdownAdaptor(QObject *parent);
    virtual ~DBusShutdownAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Restart();
    void Show();
    void Shutdown();
    bool ShutdownVisible();
Q_SIGNALS: // SIGNALS
};

#endif
